export const availableSkills = [
  "JavaScript",
  "React",
  "Node.js",
  "CSS",
  "HTML",
  "Python",
  "Java",
  "C++",
  "C#",
  "PHP",
  "Ruby",
  "TypeScript",
  "Swift",
  "Kotlin",
  "Go",
  "Rust",
  "Dart",
  "SQL",
  "NoSQL",
  "MongoDB",
  "PostgreSQL",
  "MySQL",
  "Oracle",
  "SQLite",
  "GraphQL",
  "REST",
  "API Development",
  "Microservices",
  "Docker",
  "Kubernetes",
  "AWS",
  "Azure",
  "Google Cloud Platform",
  "DevOps",
  "CI/CD",
  "Git",
  "GitHub",
  "GitLab",
  "Bitbucket",
  "Jenkins",
  "Travis CI",
  "CircleCI",
  "Ansible",
  "Terraform",
  "Puppet",
  "Chef",
  "Linux",
  "Unix",
  "Windows Server",
  "Shell Scripting",
  "PowerShell",
  "Bash",
  "Networking",
  "Cybersecurity",
  "Penetration Testing",
  "Firewall Management",
  "Virtualization",
  "VMware",
  "Hyper-V",
  "Xen",
  "OpenStack",
  "IoT",
  "Embedded Systems",
  "Machine Learning",
  "Deep Learning",
  "Artificial Intelligence",
  "Data Science",
  "Data Analysis",
  "Data Visualization",
  "Pandas",
  "NumPy",
  "SciPy",
  "TensorFlow",
  "Keras",
  "PyTorch",
  "Scikit-Learn",
  "Hadoop",
  "Spark",
  "Big Data",
  "Elasticsearch",
  "Kafka",
  "Tableau",
  "Power BI",
  "MATLAB",
  "R",
  "SAS",
  "Business Intelligence",
  "Agile",
  "Scrum",
  "Kanban",
  "Project Management",
  "JIRA",
  "Confluence",
  "Asana",
  "Trello",
  "Slack",
  "Figma",
  "Adobe XD",
  "Sketch",
  "UI/UX Design",
  "Responsive Design",
  "Mobile Development",
  "Android Development",
  "iOS Development",
  "Flutter",
  "React Native",
  "Xamarin",
  "Blockchain",
  "Cryptography",
  "Ethereum",
  "Smart Contracts",
  "Solidity",
  "Web Development",
  "Frontend Development",
  "Backend Development",
  "Full Stack Development",
  "Software Architecture",
  "System Design",
  "Testing",
  "Unit Testing",
  "Integration Testing",
  "End-to-End Testing",
  "Test Automation",
  "Selenium",
  "Cypress",
  "Jest",
  "Mocha",
  "Chai",
  "Enzyme",
  "Robot Framework",
  "Performance Testing",
  "Load Testing",
  "Stress Testing",
  "Penetration Testing",
  "API Testing",
  "Mobile Testing",
  "Security Testing",
  "Usability Testing",
  "Accessibility Testing",
  "Regression Testing",
  "Functional Testing",
  "Non-Functional Testing",
  "Smoke Testing",
  "Sanity Testing",
  "Exploratory Testing",
  "Ad Hoc Testing",
  "Configuration Management",
  "Version Control",
  "Continuous Integration",
  "Continuous Deployment",
  "Continuous Delivery",
  "Infrastructure as Code",
  "Site Reliability Engineering",
  "Technical Support",
  "Help Desk",
  "IT Service Management",
  "ITIL",
  "Incident Management",
  "Problem Management",
  "Change Management",
  "Release Management",
  "Asset Management",
  "Configuration Management",
  "Service Desk",
  "IT Operations",
  "Database Administration",
  "Network Administration",
  "System Administration",
  "Cloud Computing",
  "Edge Computing",
  "Serverless Computing",
  "Distributed Systems",
  "Parallel Computing",
  "High-Performance Computing",
  "Grid Computing",
  "Cluster Computing",
  "Big Data Analytics",
  "Data Warehousing",
  "Data Lakes",
  "ETL",
  "Data Mining",
  "Business Analytics",
  "Customer Relationship Management (CRM)",
  "Enterprise Resource Planning (ERP)",
  "Supply Chain Management (SCM)",
  "Human Resources Management Systems (HRMS)",
  "Content Management Systems (CMS)",
  "Learning Management Systems (LMS)",
  "E-commerce",
  "Digital Marketing",
  "SEO",
  "SEM",
  "Social Media Marketing",
  "Email Marketing",
  "Content Marketing",
  "Affiliate Marketing",
  "Analytics",
  "Google Analytics",
  "Adobe Analytics",
  "Tag Management",
  "A/B Testing",
  "Multivariate Testing",
  "Conversion Rate Optimization (CRO)",
  "User Research",
  "Usability Testing",
  "Customer Experience (CX)",
  "User Experience (UX)",
  "User Interface (UI)",
  "Design Thinking",
  "Human-Computer Interaction (HCI)",
  "Interaction Design",
  "Visual Design",
  "Graphic Design",
  "Motion Graphics",
  "3D Modeling",
  "Augmented Reality (AR)",
  "Virtual Reality (VR)",
  "Mixed Reality (MR)",
  "Game Development",
  "Unity",
  "Unreal Engine",
  "Game Design",
  "Game Testing",
  "Game Analytics",
  "Game Marketing",
  "Sound Design",
  "Music Production",
  "Audio Engineering",
  "Video Production",
  "Video Editing",
  "Animation",
  "Storyboarding",
  "Screenwriting",
  "Film Production",
  "Broadcasting",
  "Journalism",
  "Technical Writing",
  "Content Writing",
  "Copywriting",
  "Editing",
  "Proofreading",
  "Translation",
  "Localization",
  "Content Strategy",
  "Content Management",
  "Digital Asset Management",
  "Knowledge Management",
  "Information Architecture",
  "Taxonomy",
  "Metadata Management",
  "Data Governance",
  "Data Quality",
  "Data Privacy",
  "Data Security",
  "Compliance",
  "Risk Management",
  "Business Continuity",
  "Disaster Recovery",
  "Incident Response",
  "Security Operations",
  "Threat Intelligence",
  "Vulnerability Management",
  "Penetration Testing",
  "Red Team",
  "Blue Team",
  "Purple Team",
  "Security Awareness",
  "Security Training",
  "Security Policy",
  "Security Architecture",
  "Security Engineering",
  "Security Operations Center (SOC)",
  "Incident Detection",
  "Incident Response",
  "Forensics",
  "Malware Analysis",
  "Reverse Engineering",
  "Ethical Hacking",
  "Bug Bounty",
  "Security Compliance",
  "GDPR",
  "HIPAA",
  "PCI DSS",
  "ISO 27001",
  "NIST",
  "CIS Controls",
  "OWASP",
  "SANS",
  "ISACA",
  "ISC2",
  "CSA",
  "BSIMM",
  "MITRE ATT&CK",
  "Cyber Kill Chain",
  "Threat Modeling",
  "Security Testing",
  "Application Security",
  "Network Security",
  "Endpoint Security",
  "Cloud Security",
  "Container Security",
  "Serverless Security",
  "DevSecOps",
  "Security Orchestration",
  "Security Automation",
  "Security Monitoring",
  "Security Information and Event Management (SIEM)",
  "Security Incident and Event Management (SIEM)",
  "Security Orchestration, Automation, and Response (SOAR)",
  "Extended Detection and Response (XDR)",
  "Managed Detection and Response (MDR)",
  "Security Operations Center (SOC)",
  "Incident Detection",
  "Incident Response",
  "Forensics",
  "Malware Analysis",
  "Reverse Engineering",
  "Ethical Hacking",
  "Bug Bounty",
  "Security Compliance",
  "GDPR",
  "HIPAA",
  "PCI DSS",
  "ISO 27001",
  "NIST",
  "CIS Controls",
  "OWASP",
  "SANS",
  "ISACA",
  "ISC2",
  "CSA",
  "BSIMM",
  "MITRE ATT&CK",
  "Cyber Kill Chain",
  "Threat Modeling",
  "Security Testing",
  "Application Security",
  "Network Security",
  "Endpoint Security",
  "Cloud Security",
  "Container Security",
  "Serverless Security",
  "DevSecOps",
  "Security Orchestration",
  "Security Automation",
  "Security Monitoring",
  "Security Information and Event Management (SIEM)",
  "Security Incident and Event Management (SIEM)",
  "Security Orchestration, Automation, and Response (SOAR)",
  "Extended Detection and Response (XDR)",
  "Managed Detection and Response (MDR)",
  "Security Operations Center (SOC)",
  "Incident Detection",
  "Incident Response",
  "Forensics",
  "Malware Analysis",
  "Reverse Engineering",
  "Ethical Hacking",
  "Bug Bounty",
  "Security Compliance",
  "GDPR",
  "HIPAA",
  "PCI DSS",
  "ISO 27001",
  "NIST",
  "CIS Controls",
  "OWASP",
  "SANS",
  "ISACA",
  "ISC2",
  "CSA",
  "BSIMM",
  "MITRE ATT&CK",
  "Cyber Kill Chain",
  "Threat Modeling",
  "Security Testing",
  "Application Security",
  "Network Security",
  "Endpoint Security",
  "Cloud Security",
  "Container Security",
  "Serverless Security",
  "DevSecOps",
  "Security Orchestration",
  "Security Automation",
  "Security Monitoring",
  "Security Information and Event Management (SIEM)",
  "Security Incident and Event Management (SIEM)",
  "Security Orchestration, Automation, and Response (SOAR)",
  "Extended Detection and Response (XDR)",
  "Managed Detection and Response (MDR)",
  "Security Operations Center (SOC)",
  "Incident Detection",
  "Incident Response",
  "Forensics",
  "Malware Analysis",
  "Reverse Engineering",
  "Ethical Hacking",
  "Bug Bounty",
  "Security Compliance",
  "GDPR",
  "HIPAA",
  "PCI DSS",
  "ISO 27001",
  "NIST",
  "CIS Controls",
  "OWASP",
  "SANS",
  "ISACA",
  "ISC2",
  "CSA",
  "BSIMM",
  "MITRE ATT&CK",
  "Cyber Kill Chain",
  "Threat Modeling",
  "Security Testing",
  "Application Security",
  "Network Security",
  "Endpoint Security",
  "Cloud Security",
  "Container Security",
  "Serverless Security",
  "DevSecOps",
  "Security Orchestration",
  "Security Automation",
  "Security Monitoring",
  "Security Information and Event Management (SIEM)",
  "Security Incident and Event Management (SIEM)",
  "Security Orchestration, Automation, and Response (SOAR)",
  "Extended Detection and Response (XDR)",
  "Managed Detection and Response (MDR)",
];
